In [2]:
import seaborn as sns
import metapack as mp
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display 

%matplotlib inline
sns.set_context('notebook')
mp.jupyter.init()

In [3]:
pkg = mp.jupyter.open_package()
#pkg = mp.jupyter.open_source_package()
pkg

# San Diego Police Calls for Service
`sandiego.gov-police_calls_for_service-1.1.1` Last Update: 2020-06-12T23:50:17

_San Diego Police Calls for Service, linked to related datasets_


This dataset links to the San Dieg Police Calls for Service datasets, from multiple years, combine the years and lints to the destriptions of disposition codes and beat neighborhoods.

# Caveats and Adjustments

The meaning of the numbers in the `day_of_week` column has changed from earlier
to later years. Earlier years use values from 0 to 6, while later years use
vlaues from 1 to 7. Because of this, the `day_of_week` vlaues have been re-calculated to the span from 0 to 6, where 0 is Monday and 6 is Sunday.
## Documentation Links

* [Priority codes](http://seshat.datasd.org/pd/pd_cfs_priority_defs_datasd.pdf)



## Contacts

* **Wrangler** [Eric Busboom](mailto:eric@civicknowledge.com), [Civic Knowledge](http://civicknowledge.com)

## Resources

* ** [sdpd_calls_dispositions](data/sdpd_calls_dispositions.csv)**. San Diego Police Calls for Service, 2015 to 2020
* ** [sdpd_beats](data/sdpd_beats.csv)**. San Diego Police beats
* ** [sdpd_calls_for_service](data/sdpd_calls_for_service.csv)**. San Diego Police Calls for Service, 2015 to 2020

## References
<ul><li> <strong><a href="http://seshat.datasd.org/pd/pd_calls_for_service_2015_datasd_v1.csv">calls_for_service_source_2015</a></strong>. San Diego Police Calls for Service, 2015</li><li> <strong><a href="http://seshat.datasd.org/pd/pd_calls_for_service_2016_datasd_v1.csv">calls_for_service_source_2016</a></strong>. San Diego Police Calls for Service, 2016</li><li> <strong><a href="http://seshat.datasd.org/pd/pd_calls_for_service_2017_datasd_v1.csv">calls_for_service_source_2017</a></strong>. San Diego Police Calls for Service, 2017</li><li> <strong><a href="http://seshat.datasd.org/pd/pd_calls_for_service_2018_datasd.csv">calls_for_service_source_2018</a></strong>. San Diego Police Calls for Service, 2018</li><li> <strong><a href="http://seshat.datasd.org/pd/pd_calls_for_service_2019_datasd.csv">calls_for_service_source_2019</a></strong>. San Diego Police Calls for Service, 2019</li><li> <strong><a href="http://seshat.datasd.org/pd/pd_calls_for_service_2020_datasd.csv">calls_for_service_source_2020</a></strong>. San Diego Police Calls for Service, 2020</li><li> <strong><a href="http://seshat.datasd.org/pd/pd_dispo_codes_historical_datasd.csv">disp_codes_2017</a></strong>. Disposition Codes, prior to October 17, 2017</li><li> <strong><a href="http://seshat.datasd.org/pd/pd_dispo_codes_datasd.csv">disp_codes</a></strong>. Current disposition codes</li><li> <strong><a href="http://seshat.datasd.org/pd/pd_beat_neighborhoods_datasd.csv">beat_codes</a></strong>. Beat Neighborhood Codes</li><ul>

In [8]:
disp = pkg.resource('sdpd_calls_dispositions').dataframe()
beats = pkg.resource('sdpd_beats').dataframe()
calls = pkg.resource('sdpd_calls_for_service').dataframe()
calls.dtypes

/Users/eric/proj/metatab-dev/metapack-dev/rowgenerators/rowgenerators/generator/csv.py:111: UserWarning: Error setting dtypes; NA in integer column. Try again without dtypes Exception: Integer column has NA values in column 12
  'Exception: ' + str(last_exception))

incident_num                         object
date_time                    datetime64[ns]
day_of_week                           int64
address_number_primary                int64
address_dir_primary                  object
address_road_primary                 object
address_sfx_primary                  object
address_dir_intersecting             object
address_road_intersecting            object
address_sfx_intersecting             object
call_type                            object
disposition                          object
beat                                float64
priority                            float64
dtype: object

In [10]:
calls[calls.beat.isnull()]

,incident_num,date_time,day_of_week,address_number_primary,address_dir_primary,address_road_primary,address_sfx_primary,address_dir_intersecting,address_road_intersecting,address_sfx_intersecting,call_type,disposition,beat,priority
1183,P15010001264,2015-01-01 15:27:47,3,0,NaN,4EIE012 3500 KETT,NaN,NaN,NaN,NaN,1150,DUP,NaN,1.0
4731,P15010005056,2015-01-03 20:40:34,5,0,NaN,822U2,NaN,NaN,NaN,NaN,CC,CAN,NaN,3.0
11495,P15010012254,2015-01-08 01:56:06,3,0,NaN,6HBY590 9242 MIRAMAR,NaN,NaN,NaN,NaN,1150,DUP,NaN,1.0
12323,P15010013128,2015-01-08 15:04:38,3,0,NaN,CMB,NaN,NaN,LYMERIC,NaN,WARRANT,DUP,NaN,3.0
16864,P15010017989,2015-01-11 08:22:22,6,10,NaN,61,NaN,NaN,NaN,NaN,WARRANT,DUP,NaN,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1659118,P17100024635,2017-10-15 19:28:49,6,3900,NaN,CLAIREMONT,DR,NaN,NaN,NaN,MCTSTP,NaN,NaN,1.0
1660008,P17100025571,2017-10-16 11:13:35,0,0,NaN,1100 MADDEN,NaN,NaN,CORONADO,NaN,MCTSTP,NaN,NaN,1.0
1660058,P17100025625,2017-10-16 11:50:27,0,0,NaN,NaN,NaN,NaN,NaN,NaN,MCTSTP,NaN,NaN,1.0
1660246,P17100025821,2017-10-16 14:07:40,0,4500,NaN,COLLEGE,NaN,NaN,NaN,NaN,MCTSTP,NaN,NaN,1.0
1660524,P17100026116,2017-10-16 17:05:46,0,400,NaN,ASH,ST,NaN,NaN,NaN,MCTSTP,NaN,NaN,1.0